const now = new Date();
const feed = [
  { date: Date.now(), messageTitle: 'You add a new transaction', messageBody: 'You add an expense transaction on foo.bar' },
  { date: new Date().setTime(now.getTime() + (20 * 60 * 1000)), messageTitle: 'Adi added a new budget!', messageBody: 'Adi add a new budget for movies, it\'s includes food, movies, and dvd categories.' },
  { date: new Date(), messageTitle: 'Check how can you save 10 shakels each month on food', messageBody: 'Just eat less..' },
  { date: new Date(), messageTitle: 'Feed title 1', messageBody: 'Feed body 1' },
  { date: new Date(), messageTitle: 'Feed title 2', messageBody: 'Feed body 2' },
  { date: new Date(), messageTitle: 'Feed title 3', messageBody: 'Feed body 3' },
  { date: new Date(), messageTitle: 'Feed title 4', messageBody: 'Feed body 4' },
  { date: new Date(), messageTitle: 'Feed title 5', messageBody: 'Feed body 5' },
  { date: new Date(), messageTitle: 'Feed title 6', messageBody: 'Feed body 6' },
  { date: new Date(), messageTitle: 'Feed title 7', messageBody: 'Feed body 7' },
  { date: new Date(), messageTitle: 'Feed title 8', messageBody: 'Feed body 8' },
  { date: new Date(), messageTitle: 'Feed title 9', messageBody: 'Feed body 9' },
  { date: new Date(), messageTitle: 'Feed title 10', messageBody: 'Feed body 10' },
  { date: new Date(), messageTitle: 'Feed title 11', messageBody: 'Feed body 11' },
  { date: new Date(), messageTitle: 'Feed title 12', messageBody: 'Feed body 12' },
  { date: new Date(), messageTitle: 'Feed title 13', messageBody: 'Feed body 13' },
  { date: new Date(), messageTitle: 'Feed title 14', messageBody: 'Feed body 14' },
  { date: new Date(), messageTitle: 'Feed title 15', messageBody: 'Feed body 15' },
  { date: new Date(), messageTitle: 'Feed title 16', messageBody: 'Feed body 16' },
  { date: new Date(), messageTitle: 'Feed title 17', messageBody: 'This is a long message just to test how are the line getting orderd, because the top should be at the some line but the bottom should not.' },
  { date: new Date(), messageTitle: 'Feed title 18', messageBody: 'Feed body 18' },
  { date: new Date(), messageTitle: 'Feed title 19', messageBody: 'Feed body 19' },
  { date: new Date(), messageTitle: 'Feed title 20', messageBody: 'Feed body 20' },
  { date: new Date(), messageTitle: 'Feed title 21', messageBody: 'Feed body 21' },
  { date: new Date(), messageTitle: 'Feed title 22', messageBody: 'Feed body 22' },
  { date: new Date(), messageTitle: 'Feed title 23', messageBody: 'Feed body 23' },
  { date: new Date(), messageTitle: 'Feed title 24', messageBody: 'Feed body 24' },
  { date: new Date(), messageTitle: 'Feed title 25', messageBody: 'Feed body 25' },
  { date: new Date(), messageTitle: 'Feed title 26', messageBody: 'Feed body 26' },
  { date: new Date(), messageTitle: 'Feed title 27', messageBody: 'Feed body 27' },
  { date: new Date(), messageTitle: 'Feed title 28', messageBody: 'Feed body 28' },
  { date: new Date(), messageTitle: 'Feed title 29', messageBody: 'Feed body 29' },
  { date: new Date(), messageTitle: 'Feed title 30', messageBody: 'Feed body 30' },
];

exports.feed = feed;
