const categories = [
  { name: 'Salary', icon: 'account_balance', color: '#F44336' },
  { name: 'Food', icon: 'shopping_cart', color: '#E91E63' },
  { name: 'Packages', icon: 'local_shipping', color: '#9C27B0' },
  { name: 'Shopping', icon: 'shopping_cart', color: '#673AB7' },
  { name: 'Bar', icon: 'local_bar', color: '#3F51B5' },
  { name: 'Business', icon: 'business', color: '#2196F3' },
  { name: 'Car', icon: 'directions_car', color: '#03A9F4' },
  { name: 'Public Transportation', icon: 'directions_bus', color: '#00BCD4' },
  { name: 'Restaurant', icon: 'restaurant', color: '#009688' },
  { name: 'Movies', icon: 'theaters', color: '#4CAF50' },
  { name: 'Gas', icon: 'local_gas_station', color: '#8BC34A' },
  { name: 'Cafe', icon: 'local_cafe', color: '#CDDC39' },
  { name: 'Taxi', icon: 'local_taxi', color: '#FFEB3B' },
  { name: 'Hotel', icon: 'local_hotel', color: '#FFC107' },
  { name: 'Florist', icon: 'local_florist', color: '#FF9800' },
  { name: 'Golf', icon: 'golf_course', color: '#FF5722' },
  { name: 'Fitness', icon: 'fitness_center', color: '#795548' },
  { name: 'Vacation', icon: 'beach_access', color: '#9E9E9E' },
  { name: 'Cigarette', icon: 'smoking_rooms', color: '#607D8B' },
  { name: 'Board Games', icon: 'casino', color: '#000000' },
  { name: 'School', icon: 'school', color: '#FFFFFF' },
  { name: 'Baby', icon: 'child_care', color: '#F44336' },
  { name: 'Camera', icon: 'camera_alt', color: '#9C27B0' },
  { name: 'Computer', icon: 'computer', color: '#FFEB3B' },
  { name: 'Smartphone', icon: 'smartphone', color: '#4CAF50' },
  { name: 'Headset', icon: 'headset', color: '#9E9E9E' },
  { name: 'Health', icon: 'favorite', color: '#2196F3' },
  { name: 'Home', icon: 'home', color: '#E91E63' },
  { name: 'Furniture', icon: 'weekend', color: '#009688' },
];

exports.categories = categories;
