const now = new Date();
const feed = [
  { date: Date.now(), message_title: 'You add a new transaction', message_body: 'You add an expense transaction on foo.bar' },
  { date: new Date().setTime(now.getTime() + (20 * 60 * 1000)), message_title: 'Adi added a new budget!', message_body: 'Adi add a new budget for movies, it\'s includes food, movies, and dvd categories.' },
  { date: new Date(), message_title: 'Check how can you save 10 shakels each month on food', message_body: 'Just eat less..' },
  { date: new Date(), message_title: 'Feed title 1', message_body: 'Feed body 1' },
  { date: new Date(), message_title: 'Feed title 2', message_body: 'Feed body 2' },
  { date: new Date(), message_title: 'Feed title 3', message_body: 'Feed body 3' },
  { date: new Date(), message_title: 'Feed title 4', message_body: 'Feed body 4' },
  { date: new Date(), message_title: 'Feed title 5', message_body: 'Feed body 5' },
  { date: new Date(), message_title: 'Feed title 6', message_body: 'Feed body 6' },
  { date: new Date(), message_title: 'Feed title 7', message_body: 'Feed body 7' },
  { date: new Date(), message_title: 'Feed title 8', message_body: 'Feed body 8' },
  { date: new Date(), message_title: 'Feed title 9', message_body: 'Feed body 9' },
  { date: new Date(), message_title: 'Feed title 10', message_body: 'Feed body 10' },
  { date: new Date(), message_title: 'Feed title 11', message_body: 'Feed body 11' },
  { date: new Date(), message_title: 'Feed title 12', message_body: 'Feed body 12' },
  { date: new Date(), message_title: 'Feed title 13', message_body: 'Feed body 13' },
  { date: new Date(), message_title: 'Feed title 14', message_body: 'Feed body 14' },
  { date: new Date(), message_title: 'Feed title 15', message_body: 'Feed body 15' },
  { date: new Date(), message_title: 'Feed title 16', message_body: 'Feed body 16' },
  { date: new Date(), message_title: 'Feed title 17', message_body: 'Feed body 17' },
  { date: new Date(), message_title: 'Feed title 18', message_body: 'Feed body 18' },
  { date: new Date(), message_title: 'Feed title 19', message_body: 'Feed body 19' },
  { date: new Date(), message_title: 'Feed title 20', message_body: 'Feed body 20' },
  { date: new Date(), message_title: 'Feed title 21', message_body: 'Feed body 21' },
  { date: new Date(), message_title: 'Feed title 22', message_body: 'Feed body 22' },
  { date: new Date(), message_title: 'Feed title 23', message_body: 'Feed body 23' },
  { date: new Date(), message_title: 'Feed title 24', message_body: 'Feed body 24' },
  { date: new Date(), message_title: 'Feed title 25', message_body: 'Feed body 25' },
  { date: new Date(), message_title: 'Feed title 26', message_body: 'Feed body 26' },
  { date: new Date(), message_title: 'Feed title 27', message_body: 'Feed body 27' },
  { date: new Date(), message_title: 'Feed title 28', message_body: 'Feed body 28' },
  { date: new Date(), message_title: 'Feed title 29', message_body: 'Feed body 29' },
  { date: new Date(), message_title: 'Feed title 30', message_body: 'Feed body 30' },
];

exports.feed = feed;
